#!/usr/bin/env python3
import requests, json, time

ORCHESTRATOR_URL = "http://localhost:8000/api/command"

clones = [
    # --- Original 12 ---
    {"name":"Notewave","description":"AI notepad for meetings","prompt":"A futuristic, glowing waveform shaped like a fountain pen, dark background, electric blue and neon purple.","link":"#","spec":{"name":"Notewave","description":"AI notepad for meetings","prompt":"A futuristic, glowing waveform shaped like a fountain pen, dark background, electric blue and neon purple."}},
    {"name":"AdVivid","description":"AI video ad generator","prompt":"A vibrant, abstract explosion of color shaped like a play button, cyberpunk palette, neon pink and cyan.","link":"#","spec":{"name":"AdVivid","description":"AI video ad generator","prompt":"A vibrant, abstract explosion of color shaped like a play button, cyberpunk palette, neon pink and cyan."}},
    {"name":"ScribeBridge","description":"Chrome extension for notebook exports","prompt":"A stylized bridge made of glowing data streams connecting a notebook to a cloud, tech-blue and white.","link":"#","spec":{"name":"ScribeBridge","description":"Chrome extension for notebook exports","prompt":"A stylized bridge made of glowing data streams connecting a notebook to a cloud, tech-blue and white."}},
    {"name":"Autonomo","description":"AI agent builder","prompt":"A geometric, robotic eye, metallic gold and dark steel, futuristic.","link":"#","spec":{"name":"Autonomo","description":"AI agent builder","prompt":"A geometric, robotic eye, metallic gold and dark steel, futuristic."}},
    {"name":"CaptureCraft","description":"UI screenshot capture","prompt":"A perfect, digital square with a stylized camera lens, soft gradients, UI/UX design.","link":"#","spec":{"name":"CaptureCraft","description":"UI screenshot capture","prompt":"A perfect, digital square with a stylized camera lens, soft gradients, UI/UX design."}},
    {"name":"FusionGate","description":"OpenRouter-style aggregator","prompt":"An interdimensional, glowing portal made of interconnected nodes, cosmic purple and teal.","link":"#","spec":{"name":"FusionGate","description":"OpenRouter-style aggregator","prompt":"An interdimensional, glowing portal made of interconnected nodes, cosmic purple and teal."}},
    {"name":"RouteMind","description":"LLM router","prompt":"A stylized, glowing brain with branching neon pathways, green and blue matrix.","link":"#","spec":{"name":"RouteMind","description":"LLM router","prompt":"A stylized, glowing brain with branching neon pathways, green and blue matrix."}},
    {"name":"ZeroLink","description":"Zero-cost LLM router","prompt":"A minimalist, glowing zero symbol with a chain link inside, bright green and black.","link":"#","spec":{"name":"ZeroLink","description":"Zero-cost LLM router","prompt":"A minimalist, glowing zero symbol with a chain link inside, bright green and black."}},
    {"name":"ClipForge","description":"Short-video generator","prompt":"An anvil with a spark of energy striking it, orange and dark industrial.","link":"#","spec":{"name":"ClipForge","description":"Short-video generator","prompt":"An anvil with a spark of energy striking it, orange and dark industrial."}},
    {"name":"VidCraft","description":"Automated YouTube shorts","prompt":"A stylized film reel transforming into a rocket, gold and deep red.","link":"#","spec":{"name":"VidCraft","description":"Automated YouTube shorts","prompt":"A stylized film reel transforming into a rocket, gold and deep red."}},
    {"name":"Lumina","description":"Open-source GLM inference","prompt":"A glowing, central core of light with rings of data orbiting it, bright ethereal gold and white.","link":"#","spec":{"name":"Lumina","description":"Open-source GLM inference","prompt":"A glowing, central core of light with rings of data orbiting it, bright ethereal gold and white."}},
    {"name":"CodeForge","description":"OpenCode coding agent","prompt":"A glowing, stylized hammer and code brackets, neon blue and dark slate.","link":"#","spec":{"name":"CodeForge","description":"OpenCode coding agent","prompt":"A glowing, stylized hammer and code brackets, neon blue and dark slate."}},
    # --- New apps ---
    {"name":"Piece Logic Copy","description":"A tool for logic-based copy and content generation.","prompt":"A digital logic board with glowing connections, cyberpunk style, neon blue and purple, futuristic interface.","link":"https://piece-logic-copy-c0882f22.base44.app","spec":{"name":"Piece Logic Copy","description":"A tool for logic-based copy and content generation.","prompt":"A digital logic board with glowing connections, cyberpunk style, neon blue and purple, futuristic interface."}},
    {"name":"Manifest AI","description":"Transform your stories into cinematic long-form videos with AI-powered scene generation, memory-linked continuity, and professional editing tools.","prompt":"A cinematic film reel transforming into glowing AI neural networks, cyberpunk style, neon blue and purple, dark background, professional video editing vibe.","link":"https://manifest-video-flow.base44.app","spec":{"name":"Manifest AI","description":"Transform your stories into cinematic long-form videos with AI-powered scene generation, memory-linked continuity, and professional editing tools.","prompt":"A cinematic film reel transforming into glowing AI neural networks, cyberpunk style, neon blue and purple, dark background, professional video editing vibe."}},
    {"name":"AuraVision (Copy)","description":"Discover and visualize the hidden energy frequencies around you. AuraVision uses your device's camera and microphone to provide a mesmerizing, real-time interpretation of a person's aura and energetic vibrations.","prompt":"A glowing human aura with vibrant colorful energy waves, cyberpunk style, dark background, mystical energy visualization.","link":"https://aura-vision-copy-6da627db.base44.app","spec":{"name":"AuraVision (Copy)","description":"Discover and visualize the hidden energy frequencies around you. AuraVision uses your device's camera and microphone to provide a mesmerizing, real-time interpretation of a person's aura and energetic vibrations.","prompt":"A glowing human aura with vibrant colorful energy waves, cyberpunk style, dark background, mystical energy visualization."}}
]

login_resp = requests.post("http://localhost:8000/api/login", json={"username":"admin","password":"YOUR_ADMIN_PASSWORD"}).json()
headers = {"Authorization": f"Bearer {login_resp['access_token']}", "Content-Type": "application/json"}

for clone in clones:
    payload = {"command": "deploy_clone", "params": {"name": clone["name"], "description": clone["description"], "prompt": clone["prompt"], "link": clone.get("link", "#"), "spec": clone["spec"]}}
    resp = requests.post(ORCHESTRATOR_URL, json=payload, headers=headers)
    print(f"✅ {clone['name']}" if resp.ok else f"❌ {clone['name']}: {resp.text}")
    time.sleep(0.5)